### ISSUE TITLE
S1: give player choice and not force progression

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/A_Little_Adventure#33]
Current Behavior:

Scenario progresses as soon as 1 leader is defeated.

Expectation:

Option Message Prompt displayed which allows progression or kill the other leader (which will progress to the next scenario without prompt).

**Comment by cooljeanius** [comment]
I added a note explaining things a bit in 026cbea; the reason they can't both be killed in the first scenario is because the second one is always killing the other one you didn't kill previously, so, if you kill both in the first one, there's no second scenario. I suppose the campaign could just skip directly to the 3rd scenario, but then the player wouldn't have a trapper with them to fulfill the "scout" role and explain the situation to them.

**Comment by cooljeanius** [comment]
I guess one thing I could do to improve things further would be to move the units in the victory cutscene to actually *show* the other leader escaping...

**Comment by cooljeanius** [comment]
> I guess one thing I could do to improve things further would be to move the units in the victory cutscene to actually _show_ the other leader escaping...

...and maybe also some additional dialogue when first attacking the enemy leaders...

**Comment by cooljeanius** [comment]
ok I'm going to consider this closed as of [663fe07](https://github.com/cooljeanius/A_Little_Adventure/commit/663fe074e911b819e5f902b84210233f3e401f3b).
